// File generated by the Flutter Fire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWK4GTERjJRMduV-aS1kTpSViSdroc-EM',
    appId: '1:487224929410:web:4c9b55b5a4421c6d19989b',
    messagingSenderId: '487224929410',
    projectId: 'appproject2-f2777',
    authDomain: 'appproject2-f2777.firebaseapp.com',
    storageBucket: 'appproject2-f2777.firebasestorage.app',
    measurementId: 'G-D03H3FKYDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqY7EzMV96cbQGLX4Zhyv1RnYhVRA_52U',
    appId: '1:487224929410:android:aec84014dee014f719989b',
    messagingSenderId: '487224929410',
    projectId: 'appproject2-f2777',
    storageBucket: 'appproject2-f2777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOKG_QqUB0l5bZ2TWJY_lBfkYmM-jpXZQ',
    appId: '1:487224929410:ios:9289ccf82811981b19989b',
    messagingSenderId: '487224929410',
    projectId: 'appproject2-f2777',
    storageBucket: 'appproject2-f2777.firebasestorage.app',
    iosBundleId: 'com.example.problemSolversHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOKG_QqUB0l5bZ2TWJY_lBfkYmM-jpXZQ',
    appId: '1:487224929410:ios:9289ccf82811981b19989b',
    messagingSenderId: '487224929410',
    projectId: 'appproject2-f2777',
    storageBucket: 'appproject2-f2777.firebasestorage.app',
    iosBundleId: 'com.example.problemSolversHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWK4GTERjJRMduV-aS1kTpSViSdroc-EM',
    appId: '1:487224929410:web:608a29f2aed8f1c419989b',
    messagingSenderId: '487224929410',
    projectId: 'appproject2-f2777',
    authDomain: 'appproject2-f2777.firebaseapp.com',
    storageBucket: 'appproject2-f2777.firebasestorage.app',
    measurementId: 'G-YH0CGVFFLC',
  );

  /// Linux configuration uses web credentials as REST API fallback
  /// Linux doesn't have native Firebase SDK support
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCWK4GTERjJRMduV-aS1kTpSViSdroc-EM',
    appId: '1:487224929410:web:4c9b55b5a4421c6d19989b',
    messagingSenderId: '487224929410',
    projectId: 'appproject2-f2777',
    authDomain: 'appproject2-f2777.firebaseapp.com',
    storageBucket: 'appproject2-f2777.firebasestorage.app',
    measurementId: 'G-D03H3FKYDC',
  );

}